config/routes.rb
Rails.application.routes.draw do

  get 'special/specials'

  resources :products

  get 'products_staff' => 'products#staff_index'

  root 'welcome#index'
  get 'company' => 'welcome#company'
  get 'services' => 'welcome#managed_services'
  get 'business' => 'welcome#business'
  get 'education' => 'welcome#education'

  get 'blog' => 'newsroom#index' #renamed to Blog
  resources :articles

  resources :correspondences, except: [:index, :show, :edit, :update]

  resources :feedbacks, except: [:edit, :update]

  devise_for :users
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :user, :controller => "user"
  
  get 'staff/' => 'staff#index'

  get 'reports/feedback' => 'reports#feedback'

  get 'email-disclaimer' => 'disclaimer#index'
  get 'website-disclaimer' => 'disclaimer#web'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "600x230>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title,  presence: true
	validates :title, uniqueness: true
end

app/models/correspondence.rb
class Correspondence < ActiveRecord::Base
	apply_simple_captcha

	validates 	:first_name, 
				:last_name, 
				:company, 
				:designation, 
				:contact_number, 
				:email, 
				:industry, 
				:location, 
				presence: true

	validates :contact_number, {presence: {message: "Not a valid phone number"},
								numericality: true,
								length: {minimum: 10, maximum: 15}}
	validates :email, email: true

	def self.types
		["General Enquiry",  "Consultation", "Quotation"]
	end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	apply_simple_captcha

	validates :company_name, :industry, :work_description, :feedback_description, :rating, presence: true
	validates :rating, numericality: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "600x230>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

	validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	@specials = Product.where(onSpecial: true).limit(4)
	end

	def company		
	end

	def managed_services		
	end

	def business		
	end

	def education		
	end
	
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/disclaimer_helper.rb
module DisclaimerHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/newsroom_helper.rb
module NewsroomHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/special_helper.rb
module SpecialHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/welcome/_brands.html.erb
<div class="home-section">
  <div class="container">
    <div class="row">
      <h1>Brands and Software</h1><br>
      <span>Gentron started out in 1992 as a technology reseller that offers personalised service and, though we have grown to provide so much more, we still stay true to our roots by supplying our clients with IT hardware from market-leading brands at very competitive prices. We're not just a drop-off-and-go operation though, as we aim to build long lasting relationships with our clients and continually make sure their needs are met. Every piece of hardware bought from us is backed by an on-site warranty at no extra cost to you. </span><br>

      <div class="row">
        <div class="col-xs-3">
          <a href="http://www.acer.co.za" class="thumbnail">
            <%=image_tag("brands/acer.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="https://www.apple.com/za/" class="thumbnail">
            <%=image_tag("brands/apple.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.asus.com/za/" class="thumbnail">
            <%=image_tag("brands/asus.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.dell.co.za/" class="thumbnail">
            <%=image_tag("brands/dell.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.gigabyte.co.za/" class="thumbnail">
            <%=image_tag("brands/gigabyte.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.hp.com/" class="thumbnail">
            <%=image_tag("brands/hp.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.kensington.com/" class="thumbnail">
            <%=image_tag("brands/kensington.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.lenovo.com" class="thumbnail">
            <%=image_tag("brands/lenovo.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.mcafee.com/" class="thumbnail">
            <%=image_tag("brands/mcafee.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.microsoft.com/" class="thumbnail">
            <%=image_tag("brands/ms.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.samsung.com/za/" class="thumbnail">
            <%=image_tag("brands/samsung.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.sonymobile.com/za/" class="thumbnail">
            <%=image_tag("brands/sony.jpg")%>
          </a>
        </div>
        <div class="col-xs-3 col-xs-offset-3">
          <a href="http://mecer.co.za/" class="thumbnail">
            <%=image_tag("brands/mecer.jpg")%>
          </a>
        </div>
        <div class="col-xs-3">
          <a href="http://www.symantec.com/en/za/" class="thumbnail">
            <%=image_tag("brands/SYMANTEC.jpg")%>
          </a>
        </div>

      </div>

<!--       <div class="row">
        <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/acer.jpg")%></a></div>
        <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/apple.jpg")%></a></div>
        <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/asus.jpg")%></a></div>
        <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/dell.jpg")%></a></div>
        <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/gigabyte.jpg")%></a></div>
        <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/hp.jpg")%></a></div>
      </div>
      <div class="row">
          <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/kensington.jpg")%></a></div>
          <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/lenovo.jpg")%></a></div>
          <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/mcafee.jpg")%></a></div>
          <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/ms.jpg")%></a></div>
          <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/samsung.jpg")%></a></div>
          <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/sony.jpg")%></a></div>
      </div>
      <div class="row">
          <div class="col-xs-2 col-xs-offset-3"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/mecer.jpg")%></a></div>
          <div class="col-xs-2"><a href="http://www.isasa.org/" class="thumbnail"><%=image_tag("brands/SYMANTEC.jpg")%></a></div>
      </div>

    </div> -->
  </div>  
</div>         

app/views/welcome/business.html.erb
<!-- Header -->
<header class="header-business">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"></div>
      <div class="intro-heading">Our Business Offerings</div>
    </div>
  </div>
</header>

<section id="ourServices" class="bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Moving your business to the next level through innovative ICT solutions</h2>
        <h3 class="section-subheading text-muted">We can create personalized solutions, backed by world-class support. We will help you get the most from your products, train your staff, and offer you technical expertise. We also offer finance and lease agreements to clients not looking for an outright purchase</h3>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-heart-o fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">COMMITMENT</h4>
        <p class="text-muted">
          As technology develops it has the ability to transform the way business is done. We are dedicated to ensure that your business runs as efficiently as possible. 
        </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
        <i class="fa fa-support fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">SUPPORT</h4>
        <p class="text-muted">24/7 support is critical to any business. Gentron is here to support your business though our Service Level Agreements.</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-cogs fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">TECHNOLOGY</h4>
        <p class="text-muted">Cloud based technology is becoming critical for any business. Gentron has partnered with major cloud providers to ensure our clients have the best technology and most secure data at all times.</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-user fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">RELATIONSHIPS</h4>
        <p class="text-muted">We believe in committed long term relationships with our clients. We understand the needs of our clients. </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-trophy fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">COMPETITVE ADVANTAGE </h4>
        <p class="text-muted">
          Your business will be fully equipped to develop and deliver in today's rapidly changing world. 
        </p>
      </div> 
    </div>
  </div>
</section>
<div class="container">
  <div class="row text-center">
    <a href="#contact" class="page-scroll btn btn-xl">Contact Us</a>  
  </div>
</div>
<section id="ourServices" class="bg-light-gray">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-desktop fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">ICT STRATEGY</h4>
        <p class="text-muted">
          Our team can assist you in planning for the future and developing an ICT strategy that can meet your needs where you are and scale as you grow.
        </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-chain fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">INTEGRATION</h4>
        <p class="text-muted">
          Our team can provide you with a full assessment on your current environment and assist you to successfully integrate your new technology.
        </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-briefcase fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">MANAGED SERVICES</h4>
        <p class="text-muted">
          Gentron can manage your ICT services with a Service Level Agreement. Contact us today to discuss your requirements and let us take the hassle out of your IT department.
        </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-wifi fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">WIFI IMPLEMENTATIONS AND MANAGEMENT</h4>
        <p class="text-muted">
          We are partners with some of the worlds best Wifi manufacturers. We supply and install Aruba, Rukus, Unifi. Allow us to assess your needs and provide a solution to suit. Manage all your device from one dashboard from anywhere.
        </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-dropbox fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">PROCUREMENT</h4>
        <p class="text-muted">
          Our strong relationship with South Africa’s top suppliers allow us to offer you all the IT Hardware and software you may require at best prices, guaranteed.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/company.html.erb
<!-- Header -->
<header class="header-company">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"></div>
      <div class="intro-heading">Who we are </div>
      <a href="#contact" class="page-scroll btn btn-xl">Contact Us</a>
    </div>
  </div>
</header>


<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">About Us</h2>
        <p>
          Gentron was founded in 1992 as a technology supply company, but soon grew to become one of the leading suppliers of IT support services in South Africa. We provide a whole host of services to our clients, all contributing to a full IT package, including professional support, strategic consulting and cloud computing.  
          <br><br>
          On the technology side, we provide a long list of brands, including Acer, Asus, Mecer, Gigabyte, HP, Dell, Transcend, Kensington, Samsung and Apple, along with software to provide a complete IT solution that meet the needs of our clients. Our hardware comes with an on-site warranty at no additional cost.
          <br><br>
          We don’t simply want to be service providers, but want our clients to see us as business partners helping to make their lives easier. Consider us your outsourced IT department.
          <br><br>
          <h4 class="section-subheading text-muted">VISION</h4>
          To become the preferred supplier of IT services and technology in South Africa and build on our reputation for always being accessible and reliable.
          <br><br>
          <h4 class="section-subheading text-muted">MISSION</h4>
          To provide innovative solutions that exceed client expectations and not to be a drop-off-and-go company, but build long-term relationships with clients. We are always available and virtual, meaning we can be reached for assistance over any internet enabled device from anywhere in the country.
          <br><br>
          <h4 class="section-subheading text-muted">Values</h4>          
          Open |
          Humility |
          Ethical |
          Integrity |
          Innovative |
          Reliable |
          High-performance |
        </p>      
        <br>            
        
      </div>
    </div>

  </div>
</section>

<section id="testimonials" class="bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">What Our Clients Say</h2>
        <p>
          With over 21 years’ experience, Gentron has built up a wealth of knowledge as an IT support company and hardware supplier. We don’t simply want to be service providers for our clients, but rather become something similar to business partners through long-term relationships and excellent service. See what some of our clients have had to say about us! 
          <br /><hr><br />
          <b>“Gentron will always go the extra mile, even though we are not a big corporate company. They really try to accommodate our limited financial budget.”</b><br>
          – Financial Manager for a leading private Afrikaans high school
          <br><br>
          <b>“Gentron is your one stop IT shop, from hardware, software, knowledge and skills. I would definitely recommend them.”</b><br>
          – Manager of the IT department of a private school for girls
          <br><br>
          <b>“Gentron’s service is great and reliable and their technicians are friendly. We have had no hassles and I would gladly recommend them.”</b><br>
          – ICT Director for a collection of schools in Lyme Park, Sandton
          <br><hr>
        </p>      
        <br>            
        
      </div>
    </div>

  </div>
</section>


<!-- Team Section -->
<section id="team">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Meet the Team</h2>
        <h3 class="section-subheading text-muted"></h3>
      </div>
    </div>



    <div class="row">
      <div class="col-sm-3">
        <div class="team-member">         
          <%=image_tag("../img/ernest.jpg", size: "250x250", class:"img-responsive img-circle")%>
          <h4>Ernest Skinner</h4>
          <p class="text-muted">CEO Gentron Group</p>
          <ul class="list-inline social-buttons">
            <li><a href="https://www.linkedin.com/in/ernest-skinner-79367228?authType=NAME_SEARCH&authToken=AnOp&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A97194207%2CauthType%3ANAME_SEARCH%2Cidx%3A6-1-14%2CtarId%3A1469551560885%2Ctas%3Aernest"><i class="fa fa-linkedin"></i></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="team-member">
          <%=image_tag("../img/brian.png", size: "250x250", class:"img-responsive img-circle")%>
          <h4>Brian Lou</h4>
          <p class="text-muted">Sales Director</p>
          <ul class="list-inline social-buttons">
            <li><a href="https://www.linkedin.com/in/brian-lou-53426536?authType=NAME_SEARCH&authToken=Xq_J&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A126042808%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1469551599999%2Ctas%3Abrian%20lo"><i class="fa fa-linkedin"></i></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="team-member">         
          <%=image_tag("../img/patrick.png", size: "250x250", class:"img-responsive img-circle")%>
          <h4>Patrick Massinon</h4>
          <p class="text-muted">Director</p>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="team-member">                   
          <%=image_tag("../img/divi.jpeg", size: "250x250", class:"img-responsive img-circle")%>
          <h4>Diviyesh Nathoo </h4>
          <p class="text-muted">Managing Director</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <p class="large text-muted"></p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<!-- Header -->
<header class="header-welcome">
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in">Welcome To Gentron!</div>
            <div class="intro-heading">Your trusted IT Solution Provider</div>
            <a href="#contact" class="page-scroll btn btn-xl">Contact Us</a>
        </div>
    </div>
</header>

<%if @specials.count >=1%>
<%= render 'special/specials', specials: @specials%>
<%end%>

<!-- Services Section -->
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">IT Services</h2>
                <h3 class="section-subheading text-muted"></h3>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">
                    <%=link_to "Managed Services", services_path%>
                </h4>
                <p class="text-muted">
                    Is all this technology too much to manage? Gentron can manage your ICT services with a Service
                    Level Agreement. Contact us today to discuss your requirements and let us handle seamlessly handle 
                    your IT department. Leaving you connected and in control.
                </p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">
                    <%=link_to "Product Offerings", products_path%>
                </h4>
                <p class="text-muted">
                    Gentron offers a comprehensive range of hardware and software products, as well as guidance in 
                    order to assist you in determining which components best meet your requirements.  The aim is to 
                    add value to your purchase, as the selling proposition is not just on price, but also on matching client 
                    needs with purchase options.
                </p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">                  
                    <%=link_to "Consulting Services"%>
                </h4>
                <p class="text-muted">
                    As a company which requires Gentron as an IT Outsource Company, you will quickly realize the
                    benefits of trusting us with all your IT needs as we provide strategic consulting services, high level IT support and IT consulting services which can be utilized on an ongoing or ad-hoc basis.

                </p>
            </div>
        </div>
    </div>
</section>

<section id="about" class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">About Us</h2>
                <p>
                  Gentron was founded in 1992 as a technology supply company, but soon grew to become one of the leading suppliers of IT support services in South Africa. We provide a whole host of services to our clients, all contributing to a full IT package, including professional support, strategic consulting and cloud computing.  
                  <br><br>
                  On the technology side, we provide a long list of brands, including Acer, Asus, Mecer, Gigabyte, HP, Dell, Transcend, Kensington, Samsung and Apple, along with software to provide a complete IT solution that meet the needs of our clients. Our hardware comes with an on-site warranty at no additional cost.
                  <br><br>
                  We don’t simply want to be service providers, but want our clients to see us as business partners helping to make their lives easier. Consider us your outsourced IT department.
                  <br><br>
                  <h4 class="section-subheading text-muted">VISION</h4>
                  To become the preferred supplier of IT services and technology in South Africa and build on our reputation for always being accessible and reliable.
                  <br><br>
                  <h4 class="section-subheading text-muted">MISSION</h4>
                  To provide innovative solutions that exceed client expectations and not to be a drop-off-and-go company, but build long-term relationships with clients. We are always available and virtual, meaning we can be reached for assistance over any internet enabled device from anywhere in the country.
                  <br><br>
                  <h4 class="section-subheading text-muted">Values</h4>          
                  Open |
                  Humility |
                  Ethical |
                  Integrity |
                  Innovative |
                  Reliable |
                  High-performance |
              </p>      
              <br>            
              <%= link_to "About Us", company_path, class: "page-scroll btn btn-xl"%>
          </div>
      </div>

  </div>
</section>
<!-- <section id="education">
        <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Education Solutions</h2>
                <h3 class="section-subheading text-muted">Coming soon...</h3>
                
          </div>
      </div>

  </div>
</section> -->