config/routes.rb
Rails.application.routes.draw do

  get 'special/specials'

  resources :products

  get 'products_staff' => 'products#staff_index'

  root 'welcome#index'
  get 'company' => 'welcome#company'
  get 'services' => 'welcome#managed_services'
  get 'business' => 'welcome#business'
  get 'education' => 'welcome#education'

  get 'blog' => 'newsroom#index' #renamed to Blog
  resources :articles

  resources :correspondences, except: [:index, :show, :edit, :update]

  resources :feedbacks, except: [:edit, :update]

  devise_for :users
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :user, :controller => "user"
  
  get 'staff/' => 'staff#index'

  get 'reports/feedback' => 'reports#feedback'

  get 'email-disclaimer' => 'disclaimer#index'
  get 'website-disclaimer' => 'disclaimer#web'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "600x230>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title,  presence: true
	validates :title, uniqueness: true
end

app/models/correspondence.rb
class Correspondence < ActiveRecord::Base
	apply_simple_captcha

	validates 	:first_name, 
				:last_name, 
				:company, 
				:designation, 
				:contact_number, 
				:email, 
				:industry, 
				:location, 
				presence: true

	validates :contact_number, {presence: {message: "Not a valid phone number"},
								numericality: true,
								length: {minimum: 10, maximum: 15}}
	validates :email, email: true

	def self.types
		["General Enquiry",  "Consultation", "Quotation"]
	end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	apply_simple_captcha

	validates :company_name, :industry, :work_description, :feedback_description, :rating, presence: true
	validates :rating, numericality: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "600x230>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

	validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
	
	def index
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  layout 'staff_layout'


  def index
    @users = User.all
    #excludes(:id => current_user.id) 

  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = "123456"
    @user.password_confirmation = "123456"
    if @user.save
      #flash[:notice] = "Successfully created User." 
      redirect_to user_index_path
    else
      render :action => 'new'
    end
  end

  def edit 

  end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(user_params)
      #flash[:notice] = "Successfully updated User."
      redirect_to user_index_path
    else
      render :action => 'edit'
    end
  end

  def destroy    
    if @user.destroy
      #flash[:notice] = "Successfully deleted User."
      redirect_to user_index_path
    end
  end 

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/disclaimer_helper.rb
module DisclaimerHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/newsroom_helper.rb
module NewsroomHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/special_helper.rb
module SpecialHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/user/edit.html.erb
<h1 class="page-header">Edit user</h1>

<div class="well col-lg-4">
  <div class="col-md-10">
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, class: "form-horizontal" }) do |f| %>
      <%= f.error_notification %>


        <%= f.input :email, input_html: {value: current_user.email}, required: true, autofocus: true %>

        <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
        <% end %>

        <%= f.input :current_password, hint: "we need your current password to confirm your changes", required: true %>
        <%= f.input :password, autocomplete: "off",label: "New password" , required: false %>
        <%= f.input :password_confirmation, required: false %>
        <%= f.button :submit, "Update" %>
        <%= link_to "back", :back, class: "btn btn-link" %>

    <% end %>
  </div>
</div>

app/views/user/index.html.erb
<h1>	
	<%= link_to staff_path, class: "btn btn-default" do%>
	Back
	<%end%>
	Staff with website access
	<%= link_to new_user_path, class: "btn btn-success" do%>
	<span class="fa fa-plus"></span>
	New user
	<%end%>


</h1>

<div>
	<table class="table table-bordered">
		<thead>
			<th>Email</th>
		</thead>
		<tbody>
			<%@users.each do |u|%>

			<%me = false%>
			<%me = (current_user == u) ? true : false%>

			<tr>
				<td><%=u.email%></td>
<!-- 				<td>
					<%= link_to "Edit", edit_user_registration_path(u), class:  "btn btn-xs btn-warning " %>
					<%= link_to u, method: :delete, data: {confrim: "Are you sure?"}, class: (me ? "btn btn-xs btn-danger disabled" : "btn btn-xs btn-danger ") do%>
					Delete Account
					<%end%>
				</td> -->
			</tr>
			<%end%>
		</tbody>
	</table>
</div>

app/views/user/new.html.erb
<h1 class="page-header">New user</h1>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>
<div class="well col-lg-6">
  <div class="col-md-10">
    <%= simple_form_for(@user, url: "/user", html: { class: 'form-horizontal' }) do |f|%>
      <%= f.input :email%>
      <%= f.input :password, input_html: {value: "123454678"}, hint: "Default: 123454678"%>
      <%= f.input :password_confirmation, input_html: {value: "123454678"}, hint: "Default: 123454678"%>      
      <%= f.button :submit%> 
      <%=link_to "Back", :back, class: "btn btn-link"%> 
  <%end%> 
  </div>
</div> 