config/routes.rb
Rails.application.routes.draw do

  get 'special/specials'

  resources :products

  get 'products_staff' => 'products#staff_index'

  root 'welcome#index'
  get 'company' => 'welcome#company'
  get 'services' => 'welcome#managed_services'
  get 'business' => 'welcome#business'
  get 'education' => 'welcome#education'

  get 'blog' => 'newsroom#index' #renamed to Blog
  resources :articles

  resources :correspondences, except: [:index, :show, :edit, :update]

  resources :feedbacks, except: [:edit, :update]

  devise_for :users
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :user, :controller => "user"
  
  get 'staff/' => 'staff#index'

  get 'reports/feedback' => 'reports#feedback'

  get 'email-disclaimer' => 'disclaimer#index'
  get 'website-disclaimer' => 'disclaimer#web'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "600x230>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title,  presence: true
	validates :title, uniqueness: true
end

app/models/correspondence.rb
class Correspondence < ActiveRecord::Base
	apply_simple_captcha

	validates 	:first_name, 
				:last_name, 
				:company, 
				:designation, 
				:contact_number, 
				:email, 
				:industry, 
				:location, 
				presence: true

	validates :contact_number, {presence: {message: "Not a valid phone number"},
								numericality: true,
								length: {minimum: 10, maximum: 15}}
	validates :email, email: true

	def self.types
		["General Enquiry",  "Consultation", "Quotation"]
	end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	apply_simple_captcha

	validates :company_name, :industry, :work_description, :feedback_description, :rating, presence: true
	validates :rating, numericality: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "600x230>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

	validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/correspondences_controller.rb
class CorrespondencesController < ApplicationController
  layout "corres_layout"
    before_action :authenticate_user!, except: [:new, :create]

  before_action :set_correspondence, only: [:show, :edit, :update, :destroy]


  respond_to :html

  def index
    @correspondences = Correspondence.all
    respond_with(@correspondences)
  end

  def show
    respond_with(@correspondence)
  end

  def new
    @correspondence = Correspondence.new
    respond_with(@correspondence)
  end

  def edit
  end

  def create
    @correspondence = Correspondence.new(correspondence_params)
    if @correspondence.save
      ContactMailer.contact_email(@correspondence).deliver
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    @correspondence.update(correspondence_params)
    respond_with(@correspondence)
  end

  def destroy
    @correspondence.destroy
    respond_with(@correspondence)
  end

  private
    def set_correspondence
      @correspondence = Correspondence.find(params[:id])
    end

    def correspondence_params
      params.require(:correspondence).permit(:corres_type, :first_name, :last_name, :company, :designation, :contact_number, :email, :industry, :location, :additional_info, :captcha, :captcha_key)
    end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/correspondences_helper.rb
module CorrespondencesHelper
end

app/helpers/disclaimer_helper.rb
module DisclaimerHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/newsroom_helper.rb
module NewsroomHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/special_helper.rb
module SpecialHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/correspondences/_form.html.erb
<div class="well col-lg-9">
  <div class="col-md-11">
    <%= simple_form_for(@correspondence, html: {class: "form-horizontal"}) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :corres_type, label: "Request" , collection: Correspondence.types, selected: 1%>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :company %>
        <%= f.input :designation %>
        <%= f.input :contact_number, :input_html => { :maxlength => 10, }, hint: "999-999-9999" %>
        <%= f.input :email %>
        <%= f.input :industry %>
        <%= f.input :location %>
        <%= f.input :additional_info %>
        <%= f.simple_captcha(:object=>"correspondence",:label => "Are you a human?") %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Send"%>
        <%= link_to 'Back', :back, class: "btn btn-link" %>
      </div>
    <% end %>    
  </div>  
</div>

app/views/correspondences/edit.html.erb
<h1>Editing correspondence</h1>

<%= render 'form' %>

<%= link_to 'Show', @correspondence %> |
<%= link_to 'Back', correspondences_path %>

app/views/correspondences/index.html.erb
<h1>Listing correspondences</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Company</th>
      <th>Designation</th>
      <th>Contact number</th>
      <th>Email</th>
      <th>Industry</th>
      <th>Location</th>
      <th>Additional info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @correspondences.each do |correspondence| %>
      <tr>
        <td><%= correspondence.first_name %></td>
        <td><%= correspondence.last_name %></td>
        <td><%= correspondence.company %></td>
        <td><%= correspondence.designation %></td>
        <td><%= correspondence.contact_number %></td>
        <td><%= correspondence.email %></td>
        <td><%= correspondence.industry %></td>
        <td><%= correspondence.location %></td>
        <td><%= correspondence.additional_info %></td>
        <td><%= link_to 'Show', correspondence %></td>
        <td><%= link_to 'Edit', edit_correspondence_path(correspondence) %></td>
        <td><%= link_to 'Destroy', correspondence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Correspondence', new_correspondence_path %>

app/views/correspondences/new.html.erb
<h1 class="page-header">Request for Quote/Consultation</h1>

<%= render 'form' %>

app/views/correspondences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @correspondence.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @correspondence.last_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @correspondence.company %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @correspondence.designation %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @correspondence.contact_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @correspondence.email %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @correspondence.industry %>
</p>

<p>
  <strong>Location:</strong>
  <%= @correspondence.location %>
</p>

<p>
  <strong>Additional info:</strong>
  <%= @correspondence.additional_info %>
</p>

<%= link_to 'Edit', edit_correspondence_path(@correspondence) %> |
<%= link_to 'Back', correspondences_path %>